package:
  name: taxcrunch
  version: 0.0.0
  
source:
  path: ..

requirements:
  build:
    - python
    - "taxcalc>=2.4.2"
    - "behresp>=0.9.0"
    - "paramtools>=0.10.1"
    - ipython

  run:
    - python
    - "taxcalc>=2.4.2"
    - "behresp>=0.9.0"
    - "paramtools>=0.10.1"
    - ipython

test:
  imports:
    - taxcrunch

about:
  home: https://github.com/PSLmodels/Tax-Cruncher
